- blueprint/src/web.tex
More context: https://leanprover.zulipchat.com/#narrow/stream/412902-Polynomial-Freiman-Ruzsa-conjecture/topic/.22unfolding.20triangles.22.20in.20blueprint
> showmore is fixed in leanblueprint

- FLT/Basic/Reductions.lean
- blueprint/src/chapter/ch02reductions.tex
> feat: discriminant of P.FreyCurve

- blueprint/src/chapter/ch05automorphicformexample.tex
Per title: one missing space, one word with transposed letters, one $n$ that should have been $N$.
> Fix minor typos

- FLT/AutomorphicRepresentation/Example.lean
Carefully worked out on paper, so might well be wrong :)
> Multiplication for Hurwitz numbers

- FLT/AutomorphicRepresentation/Example.lean
Mostly to verify that the multiplication works out.
> Add Hurwitz.toQuaternion

- FLT/AutomorphicRepresentation/Example.lean
> Ring instance for Hurwitz

- FLT/AutomorphicRepresentation/Example.lean
- blueprint/src/chapter/ch05automorphicformexample.tex
Also avoid using two variables called 'z'.
> Prove Hurwitz.exists_near

- FLT/GlobalLanglandsConjectures/GLnDefs.lean
Working towards sorry-free definition of automorphic form for GL_n/Q. Work carried out in the agreeable environment of the HIM in Bonn.
> finite codimension

- FLT/GlobalLanglandsConjectures/GLnDefs.lean
> more tweaks to AutomorphicFormForGLnOverQ

- docs/Gemfile
- docs/Gemfile.lock
> Pin FFI in the docs to evade ffi/ffi#1103.

- FLT/MathlibExperiments/FrobeniusRiou.lean
> Prove Mbar_deg, Mbar_monic

- FLT/AutomorphicRepresentation/Example.lean
- FLT/HIMExperiments/flatness.lean
> fill in two sorries

- README.md
Suggestion to add link to CONTRIBUTING file from README
> Proposed addition to README

- blueprint/src/chapter/AdeleMiniproject.tex
> Blueprint: IsDedekindDomain.HeightOneSpectrum.valuation_comap is done

- FLT/DedekindDomain/FiniteAdeleRing/BaseChange.lean
Claimed task from project.
Question: I am unsure if how I set my have statements up are idiomatic - since some are repeats (e.g. changing A K to B L) would it be better to rewrite them as a single have statement with variables? 
Closes #242 
Closes #242
> Definition of map A_K^f  -> A_L^f

- .github/workflows/blueprint.yml
- scripts/build_docs.sh
I forgot to update the cache folder in https://github.com/ImperialCollegeLondon/FLT/pull/334.
> chore: fix caching for the docs

- FLT.lean
- FLT/AutomorphicRepresentation/Example.lean
- FLT/DedekindDomain/FiniteAdeleRing/BaseChange.lean
- FLT/HaarMeasure/DistribHaarChar/RealComplex.lean
- FLT/Mathlib/Algebra/Group/Subgroup/Defs.lean
- FLT/Mathlib/MeasureTheory/Group/Action.lean
- FLT/Mathlib/Topology/Constructions.lean
- lake-manifest.json
> chore: bump mathlib

- FLT/NumberField/AdeleRing.lean
> Finish proof of Rat.AdeleRing.zero_discrete

- .github/workflows/blueprint.yml
- .github/workflows/create-release.yml
- .github/workflows/update.yml
See https://github.com/leanprover-community/mathlib4/commit/20c260b92867bf530bb611360824ea31b6906d02
> chore: upgrade security

- FLT/DedekindDomain/FiniteAdeleRing/BaseChange.lean
* Add proofs for adicCompletionComapContinuousAlgEquiv
* Add ContinuousSMul instance for `\oplus_{w|v} L_w`
closes #328
> L tensor K_v = \oplus_{w|v} L_w is a homeomorphism (#328)

- FLT/AutomorphicForm/QuaternionAlgebra/HeckeOperators.lean
- FLT/DedekindDomain/FiniteAdeleRing/BaseChange.lean
- FLT/DivisionAlgebra/Finiteness.lean
- FLT/Mathlib/Algebra/Algebra/Bilinear.lean
- FLT/NumberField/AdeleRing.lean
- FLT/NumberField/InfiniteAdeleRing.lean
- FLT/QuaternionAlgebra/NumberField.lean
We're spending too long building irrelevant docs. This will speed things up.
> chore: remove "import Mathlib"

- blueprint/src/chapter/ch01introduction.tex
- blueprint/src/chapter/ch02reductions.tex
- blueprint/src/chapter/ch04overview.tex
- blueprint/src/chapter/chtopbestiary.tex
> Tinkering with LaTeX

- FLT/AutomorphicForm/QuaternionAlgebra/Defs.lean
- FLT/Mathlib/RingTheory/TensorProduct/Finite.lean
- FLT/QuaternionAlgebra/NumberField.lean
There is no correct order for tensor products :-/
> chore: change order of tensor product in rigidification

- FLT/Mathlib/Analysis/SpecialFunctions/Stirling.lean
- FLT/NumberField/DiscriminantBounds.lean
As discussed here: [#FLT > Odlyzko bounds @ 💬](https://leanprover.zulipchat.com/#narrow/channel/416277-FLT/topic/Odlyzko.20bounds/near/512248433) and privately.
> feat: numeric bounds from the discriminant

- FLT/DedekindDomain/FiniteAdeleRing/BaseChange.lean
- FLT/Deformations/Algebra/InverseLimit.lean
- FLT/GlobalLanglandsConjectures/GLnDefs.lean
- FLT/HIMExperiments/flatness.lean
- FLT/Mathlib/NumberTheory/Padics/PadicIntegers.lean
- FLT/Mathlib/RingTheory/Valuation/ValuationSubring.lean
- FLT/Mathlib/Topology/Algebra/Module/ModuleTopology.lean
- FLT/NumberField/AdeleRing.lean
- FLT/QuaternionAlgebra/NumberField.lean
This PR fixes various lint errors. Hopefully #427 will pass CI after it is merged.
> chore: linter fixes

- FLT.lean
- FLT/DedekindDomain/AdicValuation.lean
- FLT/DedekindDomain/FiniteAdeleRing/BaseChange.lean
- FLT/Mathlib/RingTheory/Finiteness/Pi.lean
Uses the results from #400 to generalize the surjectivity result from  #374 to the map to the product.
Part of  #231
> L tensor K_v -> \oplus_{w|v} L_w is surjective

- blueprint/src/chapter/AdeleMiniproject.tex
- blueprint/src/chapter/QuaternionAlgebraProject.tex
Trivial PR fixing a few typos in the blueprint.
> [BLUEPRINT]: Fix typos

- FLT/DedekindDomain/AdicValuation.lean
> ResidueFieldToCompletionResidueField

- .github/workflows/blueprint.yml
For context, see this [zulip topic](https://leanprover.zulipchat.com/#narrow/channel/442935-Carleson/topic/Blueprint.20Lean.20links.20404'ed/near/516246582).
> chore: fix cache step

- blueprint/src/chapter/FujisakiProject.tex
Add more LaTeX details and \uses and better \label s.
> feat: more details of Fujisaki argument

- FLT/NumberField/Completion/Finite.lean
> Prove `NumberField.instFiniteResidueFieldAdicCompletionIntegers`

- FLT.lean
- FLT/DivisionAlgebra/Finiteness.lean
- FLT/HaarMeasure/DistribHaarChar/AdeleRing.lean
- FLT/HaarMeasure/DistribHaarChar/Basic.lean
- blueprint/lean_decls
- blueprint/src/chapter/FujisakiProject.tex
- blueprint/src/chapter/HaarCharacterProject.tex
Prep for William Coram meeting
> feat: add Fujisaki Lean sorrys

- FLT/DedekindDomain/FiniteAdeleRing/BaseChange.lean
- FLT/Mathlib/Algebra/Module/Submodule/Basic.lean
- FLT/Mathlib/Topology/Algebra/Module/ModuleTopology.lean
Part of #231 so that we can apply [Ideal.sum_ramification_inertia](https://leanprover-community.github.io/mathlib4_docs/Mathlib/NumberTheory/RamificationInertia/Basic.html#Ideal.sum_ramification_inertia) to completions.
I would prefer an approach less entangled with the rest of the base change stuff, but I think that those would be very large projects. Also it's rather slow to compile.
> O_w is finite over O_v

- FLT/DivisionAlgebra/Finiteness.lean
- blueprint/lean_decls
- blueprint/src/chapter/FujisakiProject.tex
Fujisaki blueprint now complete.
> feat: Fujisaki blueprint leanoks

- blueprint/src/chapter/FujisakiProject.tex
Tinkering with write-up (clarify arguments, fix typo).
> chore: clarifications in Fujisaki write-up

- FLT/Mathlib/Topology/Algebra/Module/ModuleTopology.lean
- FLT/NumberField/AdeleRing.lean
Assuming that the finite adele's have the module topology
> Show A L has the A K-module topology

- FLT.lean
- FLT/DedekindDomain/IntegralClosure.lean
- FLT/Mathlib/RingTheory/Localization/BaseChange.lean
- blueprint/src/chapter/AdeleMiniproject.tex
8.20 and 8.21 from the blueprint
> Add results for Dedekind domain tensor products

- FLT/HaarMeasure/HaarChar/Ring.lean
- blueprint/src/chapter/HaarCharacterProject.tex
Fixes #514.
Note that I added a μ.Regular assumption.
> feat: ringHaarChar_mul_integral

- FLT/HaarMeasure/HaarChar/Ring.lean
Also golf ringHaarChar_mul_integral.
Closes #515
> feat: prove ringHaarChar_mul_volume

- CONTRIBUTING.md
Inspired by this message on Zulip [#Is there code for X? > comap f (c • μ) = c • comap f μ @ 💬](https://leanprover.zulipchat.com/#narrow/channel/217875-Is-there-code-for-X.3F/topic/comap.20f.20.28c.20.E2.80.A2.20.CE.BC.29.20.3D.20c.20.E2.80.A2.20comap.20f.20.CE.BC/near/519711824).
> chore: make it clearer that we expect PRs from forks.

- FLT/DivisionAlgebra/Finiteness.lean
A proof of antidiag_mem_C golfed as short as I could manage.
(Hopefully I am working from a better branch now)
> Fujisakis: proof of antidiag_mem_C

- FLT/HaarMeasure/HaarChar/AddEquiv.lean
- blueprint/src/chapter/HaarCharacterProject.tex
> feat: prove mulEquivHaarChar_eq_mulEquivHaarChar_of_isOpenEmbedding

- FLT/Mathlib/Topology/Algebra/RestrictedProduct.lean
Closes #553 (unless you expected the naturality lemmas ? I just filled in the sorry)
> feat: units of restricted products are (algebraically) restricted product of the units

- FLT/AutomorphicForm/QuaternionAlgebra/HeckeOperators/Concrete.lean
- blueprint/src/chapter/HeckeOperatorProject.tex
> feat: QuotientGroup.mk_image_finite_of_compact_of_open

- FLT/Mathlib/Topology/Algebra/Group/Units.lean
- blueprint/src/chapter/HeckeOperatorProject.tex
> feat: Submonoid.units_isOpen

- FLT/Mathlib/Topology/Algebra/Group/Units.lean
> feat: ContinuousMulEquiv.piUnits

- blueprint/src/chapter/HeckeOperatorProject.tex
> fix: mark ContinuousMulEquiv.piUnits as done

- FLT/Mathlib/Topology/Algebra/RestrictedProduct.lean
> feat: fill in two sorries in RestrictedProduct

- FLT.lean
- FLT/NumberField/AdeleRing.lean
- FLT/NumberField/Completion/Finite.lean
- FLT/NumberField/FiniteAdeleRing.lean
@smmercuri you have claimed #253 but it's easy now all the relevant background stuff is merged.
> feat: adeles of a number field are locally compact

- FLT/Mathlib/Topology/Algebra/Module/ModuleTopology.lean
- FLT/NumberField/AdeleRing.lean
- FLT/NumberField/InfiniteAdeleRing.lean
> feat: adele ring is Hausdorff

- .github/workflows/blueprint.yml
- docs/upstreaming.md
- scripts/upstreaming_dashboard.py
Based on code by Yaël from https://github.com/YaelDillies/LeanCamCombi/blob/cd307b92aeb4256b7a50fcebe1a51d2dc94f1675/scripts/upstreaming_dashboard.py
> ci: add upstreaming dashboard

- FLT/Deformations/Lemmas.lean
- FLT/Deformations/RepresentationTheory/AbsoluteGaloisGroup.lean
- FLT/Deformations/RepresentationTheory/Basic.lean
- FLT/Deformations/RepresentationTheory/Etale.lean
Bumping mathlib and adding linters before merging an old PR caused problems.
> chore: fix build after previous merge

- blueprint/src/chapter/FujisakiProject.tex
Adding leanok to the blueprint for merged commits in the Fujisaki project.
> Fujisaki leanok

- blueprint/src/chapter/ch04overview.tex
The paper is looking great! This is some amazing work.
> Fix minor typo in `ch04overview.tex`

- FLT/Patching/Utils/AdicTopology.lean
- FLT/Patching/Utils/Lemmas.lean
In favour of the iff version upstream.
> chore: drop IsTopologicalGroup.isInducing_of_nhds_one
