FLT/Basic/Reductions.lean
blueprint/src/chapter/ch02reductions.tex
blueprint/src/chapter/chtopbestiary.tex

Add comment about FLT3 and fix other typos

---

.gitignore
blueprint/src/chapter/ch02reductions.tex

* `$f K\to L$ -> $f:K\to L$`
* Added some more latex auxiliary files to the gitignore
* Is `GlobalLanglandsConjectures/notes.pdf` supposed to be checked in? I get local modifications on that file because it's checked in even though it's in the .gitignore.

fix typo, add to .gitignore

---

.gitignore

This PR remove `/.venv` from the `.gitignore` since it's unique to my setup and not generalisable. 
Sorry for the previous commit.

Remove `.venv` from `.gitignore`

---

FLT/AutomorphicRepresentation/Example.lean
blueprint/src/chapter/ch05automorphicformexample.tex

The old statement didn't make sense, also fixes a typo in the blueprint.

fix statement of ZHat.multiples

---

FLT/AutomorphicRepresentation/Example.lean
FLT/EllipticCurve/Torsion.lean
lakefile.lean

The `autoImplicit` setting was not actually being applied, as the lines were commented out.
Uncommenting the lines would have resulted in breaking Std files in VSCode.
`leanOptions` is now (4.6.0?) the preferred spelling of `moreServerArgs`, which does not have this issue.
`autoImplicit` flags that one statement appears to be garbage.

Update to the newer lakefile format

---

blueprint/src/chapter/ch05automorphicformexample.tex

Fix `hyperref` warnings such as:
```console
Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `math shift' on input line 419.
```
This warning is generated `hyperref` package when it encounters a math symbol in a section heading or caption, which is not allowed in a PDF string. It automatically removes the math symbol, but it still generates a warning.
Using `\texorpdfstring{$X$}{X}` prevents the warning.

Fix `hyperref` warning

---

FLT/for_mathlib/IsCentralSimple.lean
blueprint/src/chapter/ch06automorphicrepresentations.tex

This was a pain because the API for `RingCon` is missing some things, like the ability to simplify `⊥ x y` and the fact that `r x y ↔ r 0 (y - x)`.
Once two-sided ideals are added to mathlib, I can revisit this.

A matrix ring is a central simple algebra

---

blueprint/src/chapter/ch05automorphicformexample.tex

[Lemma 5.13](https://imperialcollegelondon.github.io/FLT/blueprint/sect0004.html#QHat.canonicalForm) is done [here](https://github.com/ImperialCollegeLondon/FLT/blob/1ae6d6c0b3895b2260852cb93a7ac150f3ab9138/FLT/AutomorphicRepresentation/Example.lean#L270-L294) but the check mark is not showing.

Add missing `leanok` to lemma 5.13

---

FLT/AutomorphicRepresentation/Example.lean

Just getting my feet wet. Proves `Function.Injective ZHat →ₐ[ℤ] QHat` and `ℚ →ₐ[ℤ] QHat`, assuming that we get `Module.Flat ℤ ZHat` by torsion-freeness.

Injections into QHat

---

FLT/HIMExperiments/flatness.lean
FLT/HIMExperiments/module_topology.lean

The following proofs in the file HIMExperiments/module_topology.lean are done: 
- Module.homeomorphism_equiv (some trivial sorries)
- Module.topology_self (this was added to prove the next lemma)
- Module.prod_canonical (one of two identical cases is not filled in yet, which should probably be done after cleanup of the proof)

Completed a few sorries in HIMExperiments/module_topology.lean

---

FLT/GlobalLanglandsConjectures/GLnDefs.lean

Some progress with the sorrys in GLnDefs. 
There is still one bit missing in the definition of `lift'`. I tried stating a compatibility statement for e.symm and the Lie bracket, but somehow Lean has difficulties finding the right HMul instance. To be followed up...

GLnDefs some sorrys filled in

---

FLT/HIMExperiments/module_topology.lean

Proof of continuous_bilinear under the conditions that the modules  ``A M`` and ``A N`` are free and finite. For this we added:
- def LinearMap.smul₁ /.smul₂ the definition of left and right scalar multiplication
- instance Module.instContinuousSMul show scalar multiplicationis Continuous
- def LinearMap.prodfst /.prodsnd the definition of the projection of the product space on its components
- instance Module.instCommAdd show addition is commutative
- def LinearMap.basis₁ representation of object by there basis
- lemma continuous_bilinear

Proof of continuous_bilinear 

---

blueprint/src/chapter/ch07exampleGLn.tex

Fix LaTeX error: 
> ERROR: Label 'AutomorphicForm.GLn.weight' could not be resolved

Blueprint: Fix label error

---

.github/workflows/push.yml
.github/workflows/push_pr.yml

- Solved all warnings 
- Disk space usage seems to be reduced significantly, but I think it's nothing but a change in the variable displayed (from uncompressed to compressed size)

Bump GitHub actions

---

.github/workflows/push.yml

There is no reason for "Upload docs & blueprint artifact" action to exist twice, and indeed its duplication is currently causing CI to fail.

Deduplicate upload action

---

.github/workflows/update.yml

In brief, this workflow runs every 3 days at 8 AM UTC or can be triggered manually. It checks out the code, updates Lean project dependencies, and handles the outcome. If the update is successful, it creates a pull request (not direct push yet for precautionary reasons); if it fails, it opens an issue to notify us.
Of course let me know if you want to change anything about the scheduling.

Add update workflow

---

FLT/MathlibExperiments/FrobeniusRiou.lean
blueprint/src/chapter/FrobeniusProject.tex

Prove F_degree, M_deg_eq_F_deg, M_monic

---

FLT/MathlibExperiments/FrobeniusRiou.lean

Proved `normal` in `FrobeniusRiou.lean`
Fixes #147

Proved that L/K is normal

---

FLT.lean

Tidy up FLT.lean

---

FLT/DedekindDomain/FiniteAdeleRing/BaseChange.lean

Claimed task from project
Closes #205

Beef up ring homomorphism to an algebra homomorphism task

---

FLT/DedekindDomain/FiniteAdeleRing/BaseChange.lean
FLT/Mathlib/Algebra/Order/Hom/Monoid.lean
FLT/Mathlib/Algebra/Order/Monoid/Unbundled/TypeTags.lean

Code dictated by Yaël
Closes #204

feat: Prove continuity of map K_v -> L_w 

---

FLT/DedekindDomain/FiniteAdeleRing/BaseChange.lean

finish `adicCompletionTensorComapContinuousAlgHom`

---

FLT/NumberField/AdeleRing.lean

A bit ugly. There is a bug in `norm_cast` being exposed here that I couldn't minimize. We could also "clean up the mess" by making `omega` more robust against this failure.

chore: `|x| < 1` implies `x = 0` for `x : Int`

---

blueprint/src/web.tex

This PR makes the dependency graph’s color scheme explicit and easily editable.
Closes #69

[BLUEPRINT]: Make the dependency graph colour scheme explicit

---

FLT/NumberField/AdeleRing.lean

The rationals are discrete in the adeles of the rationals

---

FLT/ForMathlib/DomMulActMeasure.lean
FLT/HaarMeasure/DistribHaarChar.lean

#223 made me realise that the definition of  `DistribHaarChar` was off by a "multiplicative sign" i.e. an inverse (for example `lemma distribHaarChar_real (x : ℝˣ) : distribHaarChar ℝ x = ‖(x : ℝ)‖₊⁻¹ := ...` is proved in that PR, which was not what was supposed to happen) . The sign in the Lean currently doesn't agree with the sign in the docstring or the sign in the associated Zulip discussion. This PR changes the definition to make it correct.

chore: fix sign in DistribHaarChar

---

FLT/Deformations/RepresentationTheory/Irreducible.lean
FLT/Deformations/RepresentationTheory/Subrepresentation.lean
FLT/Mathlib/LinearAlgebra/Span/Defs.lean
FLT/Mathlib/RepresentationTheory/Basic.lean

Co-authored-by: Yaël Dillies yael.dillies@gmail.com

feat(RepresentationTheory): Adds Subrepresentations

---

FLT/Mathlib/NumberTheory/NumberField/Basic.lean
FLT/Mathlib/RingTheory/DedekindDomain/AdicValuation.lean
FLT/NumberField/AdeleRing.lean

We fill in a sorry in the proof that there's an open subset of the adeles of Q whose intersection with Q is {0}.

feat: progress towards Rat.AdeleRing.zero_discrete

---

FLT/Mathlib/Algebra/IsQuaternionAlgebra.lean
FLT/QuaternionAlgebra/NumberField.lean

If D/F is an unramified quaternion algebra over a number field and S is a finite set of finite places of F, then we define the compact open subgroup U_1(S) of (D tensor_F (finite adeles of F))^*.

feat: add tame level U_1(S) for adelic quaternion algebras

---

FLT/AutomorphicForm/QuaternionAlgebra/Defs.lean

Noticed because it causes an error in documentation generation:
PANIC at _private.DocGen4.Process.InstanceInfo.0.DocGen4.Process.InstanceInfo.ofDefinitionInfo DocGen4.Process.InstanceInfo:50:39: isClass? on TotallyDefiniteQuaternionAlgebra.AutomorphicForm.add returned none

fix: TotallyDefiniteQuaternionAlgebra.AutomorphicForm.add should not be an instance

---

FLT/NumberField/AdeleRing.lean
blueprint/lean_decls
blueprint/src/chapter/AdeleMiniproject.tex
blueprint/src/chapter/FujisakiProject.tex

This swaps the theorem order in the blueprint around to generalize to all number fields and then to all elements, hopefully that's acceptable.
Closes #257

K is discrete in the adeles of K (#257)

---

.gitignore
blueprint/src/content.tex
blueprint/src/print.tex

I'd like a table of contents for the print version of the blueprint to help me navigate it more easily. Hopefully this achieves it.

feat: add table of contents

---

FLT/DedekindDomain/AdicValuation.lean
FLT/DedekindDomain/DenseIntegers.lean
FLT/DedekindDomain/FiniteAdeleRing/BaseChange.lean
FLT/Mathlib/Algebra/Algebra/Tower.lean
FLT/Mathlib/Algebra/Order/GroupWithZero.lean
FLT/Mathlib/RingTheory/TensorProduct/Basis.lean
FLT/Mathlib/Topology/Algebra/Module/Equiv.lean
FLT/Mathlib/Topology/Algebra/Module/ModuleTopology.lean
FLT/Mathlib/Topology/Algebra/Valued/ValuationTopology.lean
FLT/NumberField/AdeleRing.lean

Not the proof in the blueprint to avoid having to work with discriminants and to avoid bases as much as possible.
This also doesn't need the finite set of exceptions.
Still needs some work, but the proofs probably won't change too much now.

The map B tensor_A O_v -> \prod_{w|v} O_w is an isomorphism (#329)

---

FLT/AutomorphicForm/QuaternionAlgebra/Defs.lean

`FLT.AutomorphicForm.QuaternionAlgebra.Defs` now lints.

chore: add some docstrings for auto forms on quat algs

---

FLT/Mathlib/Topology/Algebra/Module/ModuleTopology.lean

There was an unused argument. Also add a docstring, so the file lints.

chore: get the module topology file linting.

---

.github/workflows/blueprint.yml

This PR simply bumps the TeX-Live distribution of the docker image we use to compile the blueprint.

chore: bump texlive-full distribution for docker image

---

FLT/NumberField/AdeleRing.lean

I think this was expected to depend on the definition of the base change map, but it doesn't.

Prove baseChangeEquiv_tsum_apply_right

---

FLT/HaarMeasure/HaarChar/AddEquiv.lean
FLT/HaarMeasure/HaarChar/Ring.lean

I accidentally pushed an `import Mathlib` and suddenly docs took 45 minutes to build aargh.
@YaelDillies you have a solution for this right?
Would another solution be "get CI to shake"? This might be preferred (mathlib does this, right?) Is this easy?

chore: shake

---

.github/workflows/blueprint.yml

Otherwise, this does nothing!
Also fix the CI error that should have previously been caught.

CI: checkout project during lint style

---

.github/workflows/blueprint.yml

The condition was wrong, as the workflow is triggered by push even when on non-`main` branches.

CI: don't build docs on non-`main` branches for real

---

.github/workflows/blueprint.yml

This PR replaces the docgen and blueprint steps of the workflow with [a single doc-gen action](https://github.com/leanprover-community/docgen-action). This should help in making the CI steps more consistent and easy to maintain across downstream projects. From the outside, everything should function exactly the same as before. Please see https://vierkantor.github.io/FLT for a test build of the site.

ci: Use docgen-action to build the website.

---

.github/workflows/05-pr-comment.yml
CONTRIBUTING.md

Also renamed file as not just about awaiting-review and updated contributing.md to advertise this change
Also used the javascript mechanism for doing this rather than CURL 
This addresses most of the issue #619 but possible we want to also move the tasks between columns as well
Feel free to play with this here https://github.com/Shiney/FLT/pull/2 to see if it's doing what you expect

Adjust the actions on PR comments to also add the ability to mark a PR as awaiting-author 

---

FLT/Mathlib/Topology/Algebra/Module/ModuleTopology.lean

The proposed theorem  `t2_of_finite_free` is a special case of the existing theorem `t2Space` in  `ModuleTopology`, e.g. `t2_of_finite_free` can be proven from `t2Space` by  `apply t2Space (R := R)` . 
In theorem `t2Space`, I have replaced the assumption `CommRing R`  with  `Semiring R`. 
Closes #651

t2_of_finite_free

---

FLT/AutomorphicRepresentation/Example.lean
blueprint/src/chapter/ch05automorphicformexample.tex

This pr fills in the proof of unitsrat_join_unitszHat and adds the corresponding `leanok` and dependency tags to the blueprint.

Prove unitsrat_join_unitszHat

---

FLT/AutomorphicForm/QuaternionAlgebra/Defs.lean
FLT/EllipticCurve/Torsion.lean

This PR fills in the two remaining easy sorries from AutomorphicForm/QuaternionAlgebra/Defs.lean
The proofs were found by Seed-Prover at its lightweight setting and then manually minimized by me. (For transparency, the second proof after minimization significantly differs from the original proof found by Seed-Prover, because it could not write the `instance` and did not find `Homeomorph.smul`.)

feat: complete AutomorphicForm/QuaternionAlgebra/Defs.lean

---

FLT/NumberField/AdeleRing.lean

Cocompactness of principal adeles, modulo two (groups of) sorries:
- the first sorry concerns the finite adeles of Q, where I propose that we might want to relate the `FiniteAdeleRing ℚ` API to the `QHat` API developed in chapter 5 of the blueprint;
- the second sorry concerns the infinite adeles of Q, which has already been filled in by @smmercuri [here](https://github.com/smmercuri/adele-ring_locally-compact/blob/55396f8e8de5c45780a615ee1684f510b02b4e1f/AdeleRingLocallyCompact/NumberTheory/NumberField/AdeleRing.lean#L228), but is pending my familiarization with the infinite place API. 
Co-authored-by: Salvatore Mercuri @smmercuri

feat: cocompactness of principal adeles

---

FLT/AutomorphicForm/QuaternionAlgebra/Defs.lean
FLT/AutomorphicForm/QuaternionAlgebra/FiniteDimensional.lean
FLT/AutomorphicForm/QuaternionAlgebra/HeckeOperators/Concrete.lean
FLT/AutomorphicForm/QuaternionAlgebra/HeckeOperators/Local.lean
FLT/DedekindDomain/AdicValuation.lean
FLT/DedekindDomain/FiniteAdeleRing/LocalUnits.lean
FLT/DedekindDomain/IntegralClosure.lean
FLT/Deformations/Lemmas.lean
FLT/Deformations/RepresentationTheory/IntegralClosure.lean
FLT/Mathlib/Data/Set/Prod.lean
FLT/Mathlib/Topology/Algebra/Group/Basic.lean
FLT/Mathlib/Topology/Algebra/Group/Units.lean
FLT/Mathlib/Topology/Algebra/Module/ModuleTopology.lean
FLT/Mathlib/Topology/Algebra/RestrictedProduct/Basic.lean
FLT/Mathlib/Topology/Algebra/RestrictedProduct/TopologicalSpace.lean
FLT/Mathlib/Topology/Algebra/Valued/WithZeroMulInt.lean
FLT/NumberField/AdeleRing.lean
FLT/NumberField/FiniteAdeleRing.lean
FLT/Patching/Algebra.lean
FLT/Patching/System.lean
FLT/Patching/Utils/Lemmas.lean

I'm not sure if any of these are intended to stay in the expectation that they'll be used to prove `sorry`s.
I moved the `IsLocalHom e.toRingHom` instance to prevent Lean from generating the same name for two of these similar instances.

chore: shake imports
